name: Solar
description: Flutter package for using Solar Icons.
version: 0.0.2
homepage: https://github.com/ravindudhananjaya/solar

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0





flutter:
  fonts:
    - family: SolarBold
      fonts:
        - asset: fonts/SolarBold.ttf
  
  
  
  
  
  
  
  
  
  
